# Generated by Django 4.2.4 on 2023-10-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEMP_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('phno', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
