# Generated by Django 4.2.4 on 2023-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEMP_APP', '0002_detailsclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsclass',
            name='phno',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
